### ISSUE TITLE
Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by bestickley** [hannoeru/unplugin-swc#30]
Hello, thanks so much for creating this library! Fills a big gap within Vite/Vitest community.
I'm getting this error:
```bash
Error: Dynamic require of "path" is not supported
    at file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:29:9
    at node_modules/.pnpm/picomatch@2.3.0/node_modules/picomatch/lib/picomatch.js (file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:1377:17)
    at __require2 (file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:47:50)
    at node_modules/.pnpm/picomatch@2.3.0/node_modules/picomatch/index.js (file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:1522:22)
    at __require2 (file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:47:50)
    at file:///Users/stickb/Code/niwc-pac/cosmos/node_modules/.pnpm/unplugin-swc@1.3.2_g6o72fkdx62msvhc7bd7opzgc4/node_modules/unplugin-swc/dist/index.mjs:1583:32
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

Any ideas what I'm doing wrong?

vite.config.ts
```ts
import { defineConfig } from "vite";
import swc from "unplugin-swc";

export default defineConfig({
  plugins: [swc.vite(), swc.rollup()],
});
```

tsconfig.json
```json
{
  "compilerOptions": {
"target": "esnext",
    "module": "ESNext",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "strictPropertyInitialization": false,
    "noEmit": true,
  },
  "ts-node": {
    "swc": true,
    "esm": true
  },
}
```

**Comment by StasPotapenko** [comment]
removing "type":"module" in package.json, solved the issue for me..

**Comment by bestickley** [comment]
@StasPotapenko, appreciate the tip. If anyone knows any workarounds to use this with an ESM package that would be much appreciated.

**Comment by Refzlund** [comment]
I build the project (unplugin-swc) using `tsc` and made it into a module. This resolved this error🕺

**Comment by tianyingchun** [comment]
i simply change something to fit my project type:`module`, `nodenext` https://github.com/tianyingchun/unplugin-swc-esm

it works fine, waiting latest `unplugin-swc` release
